# ASSIGNMENT-8
# TANGUDU VIJAY SANKAR
# 2105586

1. Create a null vector of size 10 but the fifth value is 1

In [1]:
print('2105586')
import numpy as np
a = np.array([0,0,0,0,1,0,0,0,0,0])
print(a)

2105586
[0 0 0 0 1 0 0 0 0 0]


2. Create a vector with values ranging from 10 to 49

In [2]:
print('2105586')
a = np.arange(10,50)
print(a)

2105586
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. Reverse a vector (first element becomes last)

In [3]:
print('2105586')
b = np.array([1,2,3,4,5,6,7,8,9])
print(b[::-1])

2105586
[9 8 7 6 5 4 3 2 1]


4. Create a 3x3 matrix with values ranging from 0 to 8
`hint: reshape`

In [4]:
print('2105586')
b = np.array([0,1,2,3,4,5,6,7,8])
print(b.reshape([3,3]))

2105586
[[0 1 2]
 [3 4 5]
 [6 7 8]]


5. Find indices of non-zero elements from [1,2,0,0,4,0]
`hint: np.nonzero`

In [5]:
print('2105586')
b = np.array([1,2,0,0,4,0])
print("indices: ",np.nonzero(b))
print(b[np.nonzero(b)])

2105586
indices:  (array([0, 1, 4], dtype=int64),)
[1 2 4]


6. Create a 3x3x3 array with random values
`hint: np.random.random`

In [6]:
print('2105586')
a = np.random.randint(0, 10, size=(3, 3, 3))
print(a)

2105586
[[[7 6 3]
  [8 5 2]
  [8 2 7]]

 [[5 2 1]
  [0 5 3]
  [8 4 2]]

 [[0 1 9]
  [8 2 1]
  [6 5 3]]]


7. Create a 10x10 array with random values and find the minimum and
maximum values
`hint: min, max`

In [7]:
print('2105586')
a = np.random.randint(0,99,size=(10,10))
print(a)
print("Min: ",a.min())
print('Max: ',a.max())

2105586
[[37 22 95 27 61 68 27 86 31 81]
 [ 0 24 24 64 83 76 33 19 18 43]
 [11 86 76 43 88 72 32 86 66 48]
 [24 81 25 73 83 90 18 64 53  6]
 [57 26 23  7 79 44 83 20 33 98]
 [11 86  9  5 79 77 12 43 39 12]
 [ 4 35 20 55 83 75 78 61 97 35]
 [ 3 16 35 91 81 86 43 32 74 26]
 [61 50 80 47 32 41 61 17  7 94]
 [ 0 80 28 57 15 35 96 23  5 31]]
Min:  0
Max:  98


8. Create a random vector of size 30 and find the mean value
`hint: mean`

In [8]:
print('2105586')
#x = np.arange()
a = np.random.randint(0,99,size=(30))
print(a)
print('Mean: ',np.mean(a))

2105586
[ 8 25 13 50 55 26 75 88 46 13 89 88 82 38 74 24  4  7 44 54 16 32 70 27
 21 17 95 11 14 58]
Mean:  42.13333333333333


9. Create a 2d array with 1 on the border and 0 inside
`hint: array[1:-1, 1:-1]`

In [9]:
print('2105586')
r = int(input('Enter matrix: '))
a = np.ones((r, r))
a[1:-1,1:-1]=0
print(a)

2105586
Enter matrix: 4
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


10. Normalize a 5x5 random matrix
`hint: (x -mean)/std`

In [10]:
print('2105586')
a = np.random.randint(0,99,size=(5,5))
mean = np.mean(a)
std = np.std(a)
normalized_a = (a - mean) / std
print('Orginal Martix')
print(a)
print('\n')
print('Normalized Martix')
print(normalized_a)

2105586
Orginal Martix
[[50 32 38 80 22]
 [24 58 12 40 71]
 [24  8 63 52 16]
 [86 22 48 61 64]
 [28  5 79 23 55]]


Normalized Martix
[[ 0.32268632 -0.44561445 -0.18951419  1.60318761 -0.87244821]
 [-0.78708146  0.66415333 -1.29928197 -0.10414744  1.21903723]
 [-0.78708146 -1.47001548  0.87757022  0.40805308 -1.12854847]
 [ 1.85928787 -0.87244821  0.23731957  0.79220346  0.92025359]
 [-0.61634795 -1.59806561  1.56050424 -0.82976483  0.53610321]]


11. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [11]:
print('2105586')
a = np.random.randint(0,20,size=(5,3))
a1 = np.random.randint(0,20,size=(3,2))
print(np.dot(a,a1))

2105586
[[238 332]
 [403 479]
 [ 70  78]
 [319 450]
 [201 311]]


12. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [12]:
print('2105586')
a = np.arange(1,11)
a[(a>2) & (a<9)] *=0
print(a)

2105586
[ 1  2  0  0  0  0  0  0  9 10]


13. Find the eigenvalues and eigenvectors of a square matrix.
`hint: np.linalg.eig`

In [13]:
print('2105586')
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

2105586
Eigenvalues:
[ 1.61168440e+01 -1.11684397e+00 -4.22209278e-16]

Eigenvectors:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


14. Find the inverse of a square matrix.
`hint: np.linalg.inv`

In [14]:
print('2105586')
r = int(input('Enter matrix size: '))
a = np.random.randint(1,20,size=(r,r))
i = np.linalg.inv(a)
print(a)
print('\nInverse')
print(np.linalg.inv(a))

2105586
Enter matrix size: 4
[[ 6 17  7  4]
 [ 4 18  5 17]
 [12 13 16 13]
 [19  2 13 19]]

Inverse
[[ 0.13259308 -0.04702809 -0.12344873  0.09862835]
 [ 0.06825604  0.01273677 -0.02906597 -0.00587851]
 [-0.09307642 -0.02746934  0.17094854 -0.07279193]
 [-0.07609406  0.06448218  0.00954351  0.00442703]]
